### ISSUE TITLE
How to set default generator for the rest of columns

### ISSUE THREAD

**Issue by everydots** [rapiddweller/rapiddweller-benerator-ce#102]
Hey:

I am an user of rapiddweller. I think it's an very good tool to generate the testing data. 

I have an question regarding to generate the csv file based on existing csv sample data. 

How to set the default behavior for all the csv columns? because I have thousands of columns to generate, I don't want to set the `attribute` for all of them. 

Could you please help me for this question ?

Thanks
Xiao Mingxing

**Comment by ake2l** [comment]
Hi Xiao, 
first you should make sure your source csv file has following filename pattern <csvname>.ent.csv to be handled as CSV entity file. This means you don't have to take care of attributes you don't want to change.

source.ent.csv

```
customer_id,customer
1,bmw
2,vw
3,ford
```

benerator.xml
```xml
<setup defaultSeparator=",">
     <import platforms="csv"/>
     <iterate type="test" source="source.ent.csv" consumer="new CSVEntityExporter('target.ent.csv')">
           <attribute name"additional" type="string"  constant="I am additional text attribute"/>
           <attribute name"customer" type="string" script="test.customer + 'i am overwriting the customer attribute and add text to it'"/>
    </iterate>
</setup>
```

If you want to specify further properties of the CSVEntityExporter, you can use a syntax like `new CSVEntityExporter{uri='target.ent.csv', append=true}`and check out our online manual 
https://www.benerator.de/ce/2.0.0/doc/component_reference.html#csventityexporter

**Comment by ake2l** [comment]
You can also check our demos , we have a similar example here https://github.com/rapiddweller/rapiddweller-benerator-ce/blob/development/src/demo/resources/demo/file/postprocess-import.ben.xml

**Comment by everydots** [comment]
Thanks very much.  But seems it can't generate number of records which larger than `source.ent.csv`. for example if only 100 lines inside or `source.ent.csv`. we only can generate no more than 100 rows :) 

Correct me if I am wrong

**Comment by ake2l** [comment]
You can do the following 

```xml
<setup defaultSeparator=",">
     <import platforms="csv"/>
     <iterate type="test" source="source.ent.csv" cyclic="true" count="1000" consumer="new CSVEntityExporter('target.ent.csv')">
           <attribute name"additional" type="string"  constant="I am additional text attribute"/>
           <attribute name"customer" type="string" script="test.customer + 'i am overwriting the customer attribute and add text to it'"/>
    </iterate>
</setup>
```

**Comment by everydots** [comment]
Got it. thanks very much. Btw, does the attribute name support regex ?

**Comment by vbergmann2** [comment]
No, an &lt;attribute&gt; is a kind of directive to generate or process a specific data field. There is no wildcard mechanism supported like regex. 

When doing an &lt;iterate&gt; over a predefined CSV file, Benerator knows all coliumn names from the CSV header row, and if a cell is missing in the CSV file, its value is imported as null in the import. So far I did not have a use case in which it really made sense to use the same anonymization or generation method for all columns.

When doing a pure &lt;generate&gt; (as indicated in your original question), you need to tell Benerator, which columns to generate - it cannot guess them. So a wildcard mechanism does not make sense there.

**Comment by vbergmann2** [comment]
However, there is a &lt;defaultComponents&gt; mechanism (see the manual) which can be used to define generation of fields which occur in many different data types (eg. audit columns in database tables) by a fixed attribute name. We will think about making this support regular expressions.
