### ISSUE TITLE
Support Milliseconds in TimeGranularity for DateTimeGenerator

### ISSUE THREAD

**Issue by PeterBrinkhoff** [rapiddweller/rapiddweller-benerator-ce#205]
The DateTimeGenerator (cp. https://docs.benerator.de/latest/component_reference.html?h=currentdate#arbitrary-date-time-generators ) does not support creating timestamps with milliseconds at the moment, which is important for many use-cases. 

Reproducer for current behavior: 

```xml
<setup>
  <generate consumer="new CSVEntityConsumer('datetimesample.csv')" type="datetimesample" count="100">
   <attribute name="DateTimeGen" generator="new DateTimeGenerator{timeGranularity='00:00:00.001'}" />
  </generate>
</setup>
```

leads to a InvalidGeneratorSetupException:
`com.rapiddweller.benerator.InvalidGeneratorSetupException: RandomLongGenerator.granularity may not be 0:`

**Describe the solution you'd like**
The TimeGranularity of the DateTimeGenerator can be configured (e.g. for one second `<property name='timeGranularity' value='00:00:01'/>`). The syntax should be extended to support a granularity of a millisecond like:

`<property name='timeGranularity' value='00:00:00.001'/>`

**Describe alternatives you've considered**
Several workarounds exists to combine the Generator Output with 3 random digits such as:

```xml
<setup>
  <generate consumer="new CSVEntityConsumer('datetimesample.csv')" type="datetimesample" count="100">
     <variable name="var_dt" generator="new DateTimeGenerator{timeGranularity='00:00:01'}" />
     <variable name="var_ms" pattern="\d{3}" />
     <attribute name="DateTimeMillisecs" script="var_dt + '.' + var_ms" />
  </generate>
</setup>
```

**Comment by vbergmann2** [comment]
I am not able to reproduce the issue, using 

```
<setup>
    <generate type="datetimesample" count="100" consumer="ConsoleExporter">
        <attribute name="DateTimeGen" generator="new DateTimeGenerator{timeGranularity='00:00:00.001'}" />
    </generate>
</setup>

```
Please make sure to use the latest release Benerator 2.1.0. Did you use a non-English defaultLocale? This might cause issues and will be fixed with the next release. If the problem persists, please attach the exception stack trace from the log file benerator.log.

Like Peter described, a workaround is to compose results of different generators. Instead of string operations, you can use number operations to get a better control of the time distribution like

```
<setup>
  <generate consumer="new CSVEntityConsumer('datetimesample.csv')" type="datetimesample" count="100">
     <variable name="var_dt" generator="new DateTimeGenerator{timeGranularity='00:00:01'}" />
     <variable name="var_ms" type="int" min="0" max="999" distribution="random" />
     <attribute name="DateTimeMillisecs" script="var_dt + var_ms" />
  </generate>
</setup>
```

**Comment by PeterBrinkhoff** [comment]
Thanks Volker :)

I can confirm that the correct locale settings let BENERATOR finish successfully without throwing any exception. 

See my locale output on Ubuntu 20.04

```bash
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

However, the output is still missing milliseconds. It is the same behavior if I add ` type="timestamp` or leave it unset in the attribute element. I can reproduce the same on __macOS 12.3 build 21E230__ with OpenJDK Runtime Environment __AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)__. 

```xml
<setup>
  <import platforms="csv"/>  
  <generate consumer="new CSVEntityExporter('datetimesample.csv')" type="datetimesample" count="100">
    
   <attribute name="dt" generator="new DateTimeGenerator{timeGranularity='00:00:00.001'}" />
   <attribute name="dt_type_timestamp" type="timestamp" generator="new DateTimeGenerator{timeGranularity='00:00:00.001'}" />

  </generate>

</setup>
```

Any idea what I might be missing?

**Comment by vbergmann2** [comment]
That's just a matter of output formatting, which can be configured by properties (eg. timestampPattern) of the CSVEntityExporter:

```
<setup>
    <import platforms="csv"/>
    <generate type="datetimesample" count="100" consumer="new CSVEntityExporter{uri='datetimesample.csv', timestampPattern='yy-MM-dd HH:mm:ss.SSS'}">
        <attribute name="dt_type_timestamp" type="timestamp" generator="new DateTimeGenerator{timeGranularity='00:00:00.001'}" />
    </generate>
</setup>

```

**Comment by PeterBrinkhoff** [comment]
You are right Volker - thanks a lot. That solved it. 

It was just a matter of formatting in the output CSV file. Hence, a database example below with TIMESTAMP datatype. 

The following snippet shows the difference in granularity and works successfully on Ubuntu and macOS: 

```xml
<setup>
  <import platforms="csv"/>  

  <database id="db" url="jdbc:h2:mem:target" driver="org.h2.Driver" user="sa" schema="PUBLIC"/>

  <execute target="db"> create table DT_TEST ( ID SERIAL NOT NULL, DT_MS TIMESTAMP, DT_SEC TIMESTAMP); </execute>

  <generate consumer="db" type="DT_TEST" count="10">
 
   <attribute name="DT_SEC" generator="new DateTimeGenerator{timeGranularity='00:00:01'}" />
   <attribute name="DT_MS" generator="new DateTimeGenerator{timeGranularity='00:00:00.001'}" />

  </generate>
  
  <iterate type="DT_TEST" source="db" consumer="new CSVEntityExporter{uri='datetimesample.csv', timestampPattern='yyyy-MM-dd HH:mm:ss.SSS'}"/>

</setup>
```

Resulting in an output file `datetimesample.csv`  as below:

```csv
ID,DT_MS,DT_SEC
1,2021-04-02 16:12:21.393,2022-02-25 13:36:42.000
2,2021-05-11 12:25:10.988,2022-03-11 13:08:34.000
3,2022-01-02 12:38:55.898,2021-06-10 10:47:16.000
4,2021-06-30 16:50:52.287,2021-05-07 10:31:31.000
5,2021-07-02 14:34:57.313,2021-09-14 09:56:59.000
6,2021-05-23 11:53:02.735,2021-10-02 13:47:52.000
7,2021-08-10 14:49:38.801,2021-08-13 16:13:04.000
8,2021-06-13 15:29:12.806,2022-02-28 11:45:10.000
9,2021-04-27 11:55:12.638,2021-11-14 14:52:05.000
10,2021-04-07 16:47:45.483,2021-09-02 10:57:23.000
```

**Comment by PeterBrinkhoff** [comment]
No update is required and timeGranularity has been documented. Issue to be closed.
