### ISSUE TITLE
unittest sometimes fail

### ISSUE THREAD

**Issue by ake2l** [rapiddweller/rapiddweller-benerator-ce#26]
- ComplexTypeGeneratorFactoryTest.testWeightedCSVImport:156->GeneratorTest.expectGeneratedSet:185->GeneratorTest.expectGeneratedSetOnce:572 expected:<[person[name=Alice, age=23], person[name=Otto, age=89]]> but was:<[person[name=Otto, age=89]]>
- StringGeneratorTest.testNonUnique:314->GeneratorTest.expectGeneratedSet:187->GeneratorTest.expectGeneratedSetOnce:572 expected:<[AA, BB, ABA, BBA, AB, AAA, ABB, AAB, BAA, BAB, BBB, BA]> but was:<[ABA, AA, BB, BBA, AB, AAA, ABB, AAB, BAA, BAB, BA]>

**Comment by vbergmann2** [comment]
Fixed
