### ISSUE TITLE
Project Wizard : java.nio.NoSuchFileException

### ISSUE THREAD

**Issue by benarso** [rapiddweller/rapiddweller-benerator-ce#27]
I am trying to create a project on windows using the benerator-wizard.

When I click the Create button, I'm getting a NoSuchFileException

java.nio.file.NoSuchFileException: C:\Program Files\rapiddweller-benerator-ce\lib\rapiddweller-benerator-ce-1.0.1 jdk-11.jar 

The file on disk is "rapiddweller-benerator-ce-1.0.1+jdk-11.jar" (with the + sign). 
I noticed that the file that the wizard is trying to access has a space in the name instead of a + sign.

**Comment by ake2l** [comment]
We know about this exception, that's why the artifact name is rapiddweller-benerator-ce-1.1.0-jdk-11.jar now ... we are pretty close to a new release. 
But the wizard is still beta and we haven't rework this component so far.
I just updated the archetype pom.xml templates which are used by the wizard.

**Comment by ake2l** [comment]
I just checked the wizard out with 1.1.0, it works in general, but usability is not really good.
I would recommend to check out the demo cases, they are pretty helpful to start.
When you want to use the wizard to create a project with database connection for testing, i would recommend to use following database connection in the wizard configuration, H2mem should work out of the box

```xml
    <setting name="database" default="h2"/>
    <setting name="dbUrl" default="jdbc:h2:mem:benerator"/>
    <setting name="dbDriver" default="org.h2.Driver"/>
    <setting name="dbSchema" default="public"/>
    <setting name="dbUser" default="sa"/>
    <setting name="dbPassword" default=""/>
```
