### ISSUE TITLE
[Help/Guide Request] Using python to write custom domains

### ISSUE THREAD

**Issue by akash-jena** [rapiddweller/rapiddweller-benerator-ce#317]
In the _scripting_ section, Python is mentioned as supported but not enabled by default but I did not find any guide or reference on how to enable it and use it in the XML. My goal is to use custom functions which can generate certain types of data and I have those functions ready in Python. So I want to integrate those custom functions to _maybe_ have a custom domain in benerator. Can someone point me in the right direction?

**Comment by ake2l** [comment]
To use python in Benerator Projects, it is necessary to configure the GraalVM as JVM properly and install python inside GraalVM. check GraalVM Docs [here](https://www.graalvm.org/22.3/docs/) .
Alternatively we also offer a preconfigured environment in our professional editions with supportive UI to achieve your goal more easy and quick if you are interested, please let us know and we can show you more.
