### ISSUE TITLE
Project wizard generated file returns Error BEN-0205 when run

### ISSUE THREAD

**Issue by HansVanEylen** [rapiddweller/rapiddweller-benerator-ce#354]
**Describe the bug**
I used the project wizard to successfully generate the files for the "Shop example database". However, when run with 
`benerator benerator.xml` (as indicated in Readme.md), it returns an error : "Error BEN-0205: Illegal attribute value for setup.defaultLineSeparator: '\r\n'. File benerator.xml, line 10"
When run with maven (as indicated in the generated readme.txt), it fails with the error "No plugin found for prefix 'benerator' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\vaneylen\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]" after showing a load of warnings that it couldn't douwnload plugin descriptors. When copying these URLs into a browser, they work without any problem.

**To Reproduce**
1. OpenJDK jdk-17.0.5+8, rapiddweller-benerator-ce-3.0.0-jdk-11 and apache-maven-3.8.7 installed
2. Start benerator-wizard
3. Select the "Shop example database"
5. Fill in the database connection details and test the connection
6. Click Create
7. Run `benerator benerator.xml` to get the first error mentioned above, or `mvn benerator:generate` to get the second error mentioned above.

**Expected behavior**
Generation of the shop example db objects (db already exists and permissions are ok)

**Additional context**
The instructions in readme.md are contradictory to what is mentioned in the readme.txt of the generated project.

**Comment by ake2l** [comment]
thanks for submitting this issue

**Comment by ake2l** [comment]
I was able to reproduce. The error is related to the extended error handling and output. We are going to provide a new version with a working wizard soon

**Comment by ake2l** [comment]
regarding your maven plugin issue ... you should execute the command `mvn benerator:generate` in the generated project directory and in your pom.xml you should have the version 3.0.0 like this ...

```              <groupId>com.rapiddweller</groupId>
                <artifactId>benerator-maven-plugin</artifactId>
                <version>3.0.0-jdk-11</version>
                <configuration>
                    <descriptor>benerator.xml</descriptor>
                    <encoding>UTF-8</encoding>
                    <validate>true</validate>
                    <dbUrl>jdbc:h2:mem:benerator</dbUrl>
                    <dbDriver>org.h2.Driver</dbDriver>
                    <dbSchema>PUBLIC</dbSchema>
                    <dbUser>sa</dbUser>
                    <dbPassword>${setup.dbPassword}</dbPassword>
                </configuration>
```

**Comment by HansVanEylen** [comment]
apparently the maven issue was caused by a network issue. I'm now using a
local Artifactory and that fixed the plugin issue.

I now get the exact same error message with maven as with the benerator
command.

**Comment by ake2l** [comment]
okay good to read, the other issues are already fixed, i am going to release a new minor version today

**Comment by ake2l** [comment]
release build is running, there were some changes which were breaking the wizard and the projects which were generated. Should work as expected now.

**Comment by HansVanEylen** [comment]
thanks ! I can confirm that it's ok now.

**Comment by ake2l** [comment]
Thanks for your feedback as well
