### ISSUE TITLE
Overwrite output table name with inserter, support also for MongoDB

### ISSUE THREAD

**Issue by ake2l** [rapiddweller/rapiddweller-benerator-ce#396]
For SQL Databases we have the possibility to change the name of an entity , this is helpful if your want to read data from one database or source and then write this entity into a different table.

This can be achieved by the following 

### Overwrite output table name with inserter

If you want to read data from one table, anonymize it and write it to a different table in the same database, you can
use a special inserter:

```xml

<iterate type="prod_user" source="db" consumer="db.inserter('anon_user')">

    <!-- anonymize here -->

</iterate>
```

!!! note

    db.inserter() is the only way to overwrite the target table name for the consumer. 
    Otherwise, Benerator will always take the type as name and assumes both source and target 
    table have the same name. 

    Using db.inserter() might also be helpful for creating staging tables 
    from multiple sources and persisting these in e.g. H2 databases. 

**Describe the solution you'd like**
I would like to have a similar solution for Mongo DB

**Comment by dangsg** [comment]
@ake2l @tunglxfast I create a PR for this issue https://github.com/rapiddweller/rapiddweller-benerator-ce/pull/398, please help me take a look and give feedback.
The idea is to create a new ComplexTypeDescriptor for target collection.

**Comment by ake2l** [comment]
Hey @dangsg i am already testing it , approach looks totally valid and it's generally working 👍 ... But still need to do some deeper tests

**Comment by tunglxfast** [comment]
I also tested and found an error when inserting into the collection itself. If the number of counters is less than 100, it's fine, but from 101 or more, the amount of data will be created infinite.
Also after inserter the _id will be different from origin table

```
<generate type="temp" count="101" consumer="mongo">
        <id name="_id" type="object" generator="MongoDBObjectIdGenerator"/>
        <attribute name="user_id" type="int" min="1" max="500" unique="true"/>
        <attribute name="product" type="string" values="'Shirt', 'Pants', 'Shoes', 'Socks'"/>
    </generate>

    <iterate type="temp" source="mongo" consumer="mongo.inserter('temp')">
        <echo>insert</echo>
    </iterate>
```

**Comment by ake2l** [comment]
Hmmm , maybe we should check this together , i tried to reproduce your infinite case, but can't , for me it seems to work properly , but maybe because of my changes regarding the entityType ...

```xml
<setup
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://www.benerator.de/schema/3.0.0"
        xsi:schemaLocation="https://www.benerator.de/schema/3.0.0 http://benerator.de/schema/rapiddweller-benerator-ce-3.0.0.xsd"
        defaultDataset="US" defaultLocale="en_US" defaultSeparator="|">

    <import platforms="db"/>

    <mongodb id="mongo" environment="environment" system="mongodb"/>
    <mongodb id="mongo2" environment="environment" system="mongodb2"/>

    <setting name="counts" value="1000"/>

    <generate type="testben2" count="{counts}" consumer="mongo">
        <id name="_id" type="object" generator="MongoDBObjectIdGenerator"/>
        <attribute name="user_id" type="int" min="1" max="100"/>
        <attribute name="amount" type="double" generator="new RandomDoubleGenerator(10, 5000, 2)"/>
        <attribute name="product" type="string" values="'Shirt', 'Pants', 'Shoes', 'Socks'"/>
    </generate>

    <echo>Check if enough data has been generated</echo>
    <iterate type="testben2" source="mongo" consumer="mongo.inserter('blbabl2'),ConsoleExporter">
        <attribute name="counter" type="int" generator="IncrementGenerator"/>
        <echo>insert</echo>
    </iterate>

    <if test="testben2.counter != counts">
        <echo lang="ftl">Wrong amount of data: ${testben2.counter} elements</echo>
    </if>
    <if test="testben2.counter == counts">
        <echo lang="ftl">Success generated ${testben2.counter} data</echo>
    </if>

    <echo>Check if enough data has been generated</echo>
    <iterate type="blbabl2" source="mongo" consumer="ConsoleExporter">
        <attribute name="counter" type="int" generator="IncrementGenerator"/>
    </iterate>

    <if test="blbabl2.counter != counts">
        <echo lang="ftl">Wrong amount of data: ${blbabl2.counter} elements</echo>
    </if>
    <if test="blbabl2.counter == counts">
        <echo lang="ftl">Success generated ${blbabl2.counter} data</echo>
    </if>
</setup>
```

**Comment by ake2l** [comment]
i am going to check in my changes as well and you check recheck if you still have this issue

**Comment by dangsg** [comment]
@ake2l Infinite loop only happens when you insert data from a collection into itself, e.g:
```
<generate type="temp" count="101" consumer="mongo">
...
<iterate type="temp" source="mongo" consumer="mongo.inserter('temp')">
...
```

**Comment by ake2l** [comment]
yeah makes totally sense ... @tunglxfast do you have a different finding ?

**Comment by tunglxfast** [comment]
just this 2 issues. Sorry my example code make some misunderstanding.

**Comment by ake2l** [comment]
test we have done so far are looking promising
