### ISSUE TITLE
More Extensive Tests for Mongo DB Implementation

### ISSUE THREAD

**Issue by ake2l** [rapiddweller/rapiddweller-benerator-ce#402]
## Checklist: More Extensive Tests for Mongo DB Implementation

- [x] **Data Generation**
  - [x] Implement the generation of documents with different levels of JSON structure, including key-value pairs, keys with lists of dictionaries, and keys with arrays of string numbers.
  - [x] Verify the functionality of distributing values via a `.wgt.csv` file using the syntax `<attribute name="example" source="data/test.wgt.csv"/>`.
  - [x] Test the capability of distributing data from different data sources, such as databases, using selectors. For example, `<attribute name="example" source="db" selector="select example from interesting_data"/>`.
These tests should be implemented in a way that they run in Github actions as E2ET or/and as integration test with Github Action Mongo DB Service 

- [x] **Data Iteration**
  - [x] Configure the iteration process to iterate over a collection filled with data from a previous Benerator run.
  - [x] Test different consumers, including LoggingExporter, MongoDB,JSON, Preview, SQL, CSV, mongodb.updater(), and mongodb.inserter('test'), to ensure proper data interaction with different collections.
  - [x] Utilize selectors with different MongoDB queries to fetch specific data subsets during iteration. This needs to be a bit more extensive , we should also test negative scenarios to check how its working with the benerator, like query data from different collection as specified in type , crosscollection queries to check data relation in different collection . We should use selectors in iterate node , variable and attribute as well ... to see how the behavior is and also check how it is working with subselector  

- [x] **Negative Cases**
  - [x] Design tests to handle scenarios where the collection being iterated is empty.
  - [x] Implement tests to handle cases where the targeted collection does not exist.

- [x] **Separate Benerator Runs**
  - [x] Execute the data generation process in one Benerator run, ensuring the generated data is stored in the Mongo DB collection.
  - [x] Conduct a separate Benerator run specifically for data iteration, validating the correctness of the iteration process independently from the generated data.

- [x] **Validation and Reporting**
  - [x] Validate that the iteration process successfully retrieves and interacts with the desired data subsets.
  - [x] Ensure that the tests for negative cases handle empty collections and non-existing targeted collections gracefully.
  - [x] Document any issues, bugs, or unexpected behavior encountered during the testing process.
  - [x] Generate a report summarizing the results of the tests and any identified areas for improvement.

**Comment by ake2l** [comment]
I just added some additional Consumer from EE edition ( artifact consumer and preview consumer) , so we should have these extended E2ET also reflected with extended consumer in our EE edition....at the moment JSON and preview still have some issues

**Comment by DanhLuong** [comment]
I will start with "Data Generation" tasks. Any problem I'll discuss with anh Tung and Dang

**Comment by ake2l** [comment]
Alright 👍 ... @tunglxfast maybe you can also show dang and danh how the tests are working in the pipeline and where they are located

**Comment by tunglxfast** [comment]
Then I will begin with Data Iteration.

**Comment by ake2l** [comment]
@DanhLuong hey danh, thanks for your contribution, could you check in the checklist above what you have covered with your PR ? thanks

**Comment by DanhLuong** [comment]
I'm still on progress on Generate Task, my intention is to push and to let member in this task review for improvement, the PR is my mistake, we shall PR after all checklist is finished

**Comment by DanhLuong** [comment]
https://github.com/rapiddweller/rapiddweller-benerator-ce/pull/416
