### ISSUE TITLE
All Generator should have a default value applicable directly to an attribute 

### ISSUE THREAD

**Issue by ake2l** [rapiddweller/rapiddweller-benerator-ce#414]
For example the Company generator , doesn't seem to have a default value like the Person or Address generator ...

so this leads to an ObjectName output like this .
<img width="1061" alt="Screenshot 2023-05-23 at 12 07 26" src="https://github.com/rapiddweller/rapiddweller-benerator-ce/assets/29091173/b3177a80-efe3-4298-9f8c-98c6f2567dff">

```xml 
 <generate type="CompanyName" count="50" consumer="Preview">
	<attribute name="name" generator="CompanyGenerator"/>
</generate>
```

we want to make sure that every generator independently of the object model behind should lead to a valid default value when directly attached to attribute.

**Comment by tunglxfast** [comment]
The CompanyGenerator belong to the benerator-ee version so it not work in this version.
In benerator-ce version we have CompanyNameGenerator instead.
Close topic.
