### ISSUE TITLE
Fail to import domain when exec "java -jar"

### ISSUE THREAD

**Issue by dangsg** [rapiddweller/rapiddweller-benerator-ce#426]
**Describe the bug**
This issue is happen when you wrap benerator-ce-3.1.0.jar into another jar, then execute with java -jar.
The root cause is that it cannot loadClass from inner jar file: spring-boot-test.jar -> benerator-ce.jar => com.rapiddweller.domain.address

**To Reproduce**
1. Create a spring boot project
2. Add benerator-ce 3.1.0 into pom.xml
3. Add a function with:
```
try (DescriptorRunner runner = new DescriptorRunner("benerator.xml", new DefaultBeneratorContext())) {
            runner.runWithoutShutdownHook();

```
4. mvn clean package: to build jar
5. java -jar target/file.jar to start spring boot server
6. Call an API to call function 3

**Expected behavior**
The behavior of "import" is very different from version 2.0.0 and 3.1.0. Need to take more time to check the different.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ake2l** [comment]
@dangsg hey dang , what about this pull request, could you give me a short update
