### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by Ramakrishnaam** [rapiddweller/rapiddweller-benerator-ce#44]
Getting  error - Execution default-cli of goal org.databene:maven-benerator-plugin:0.7.7:generate failed: An API incompatibility was encountered while executing org.databene:maven-benerator-plugin:0.7.7:generate: java.lang.ExceptionInInitializerError: null, when we tried mvn benerator:generate.

Included <variable name="person" dataset="US" generator="new com.rapiddweller.domain.person.PersonGenerator{minAgeYears='16', maxAgeYears='122'}"
                  locale="en"/> in benerator.xml

**Comment by Ramakrishnaam** [comment]
Used benerator-wizard and created a project type Generate CSV file.

inside benerator.xml included below code:

<?xml version="1.0" encoding="UTF-8"?>


<setup xmlns="https://www.benerator.de/schema/1.1.2-jdk-11"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.benerator.de/schema/1.1.2-jdk-11 benerator-1.1.2-jdk-11.xsd"
        defaultEncoding="UTF-8"
        defaultDataset="US"
        defaultLocale="en_US"
        defaultLineSeparator="\r\n">

    <generate type="transaction" count="100" consumer="CSVEntityExporter">
        <variable name="product" type="entity" source="products.ent.csv" distribution="random"/>
        <id name="id" type="long"/>
        <attribute name="comment" pattern="[A-Z][a-z]{5,12}"/>
        <attribute name="ean_code" script="product.ean_code"/>
        <attribute name="price" script="product.price"/>
        <attribute name="items" type="short" min="1" max="27"/>
        <attribute name="name" script="product.name"/>
        <attribute name="policy_nbr" script="product.policy_nbr"/>


        <variable name="person" dataset="US" generator="new com.rapiddweller.domain.person.PersonGenerator{minAgeYears='16', maxAgeYears='122'}"
                  locale="en"/>




    </generate>












    <echo>Generated data:</echo>
    <if test="com.rapiddweller.common.SystemInfo.isWindows()">
        <then>
            <execute type="shell">cmd /C type export.csv</execute>
        </then>
        <else>
            <execute type="shell">cat export.csv</execute>
        </else>
    </if>

</setup>

**Comment by ake2l** [comment]
We haven't checked the databene maven plugin so far and probalby won't check in near future, when you follow the readme or just execute and check these scripts 
https://github.com/rapiddweller/rapiddweller-benerator-ce/tree/development/script you should be able to quickstart.

Regarding the wizard this is also not in our rework scope.  the examples which are generated by the wizard might not work .
for script examples you should check the demo folder https://github.com/rapiddweller/rapiddweller-benerator-ce/tree/development/src/demo/resources/demo

**Comment by Ramakrishnaam** [comment]
Can you provide an example of SSN Generator? I am struggling to find an example.

**Comment by ake2l** [comment]
`<attribute name="ssid" generator="SSNGenerator"/>`

make sure you import the necessary domain before using it 

`<import domains="us">`

**Comment by Ramakrishnaam** [comment]
It worked thank you for the help

**Comment by ake2l** [comment]
You are welcome

**Comment by ake2l** [comment]
maybe also relevant for you, the beernator maven plugin is working , but the archetypes which are used in the wizard are outdated, this is how the pom should look like, than you can use `mvn benerator:generate` to generate your data

`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.my</groupId>
    <artifactId>simple</artifactId>
    <version>1.0</version>

    <packaging>jar</packaging>
    <name>simple data generation project</name>

    <dependencies>
        <dependency>
            <groupId>com.rapiddweller</groupId>
            <artifactId>rapiddweller-benerator-ce</artifactId>
            <version>1.1.2-jdk-11</version>
        </dependency>
    </dependencies>

    <build>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.databene</groupId>
                <artifactId>maven-benerator-plugin</artifactId>
                <version>0.7.7</version>

                <configuration>
                    <descriptor>benerator.xml</descriptor>
                    <encoding>UTF-8</encoding>
                    <validate>true</validate>
                </configuration>

                <dependencies>
                    
                    <dependency>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-api</artifactId>
                        <version>2.14.0</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-core</artifactId>
                        <version>2.14.0</version>
                    </dependency>
                </dependencies>
            </plugin>

        </plugins>
    </build>

</project>
`
