### ISSUE TITLE
[Benerator Wizard] setting MySQL driver

### ISSUE THREAD

**Issue by roxsyr** [rapiddweller/rapiddweller-benerator-ce#445]
**Describe the bug**
I need to connect with MySql Data Base, but in the benerator-wizard version 3.1.0 it isn’t in the Database Product dropbox.
I download the version 3.0.0 and MySql, it is there.
Could you help me whit this?

![Benerator Wizard](https://github.com/rapiddweller/rapiddweller-benerator-ce/assets/105430659/fb6ad8aa-e08c-455f-9763-fa752734a19e)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by ake2l** [comment]
Hello [roxsyr](https://github.com/roxsyr),

Thank you for your interest in the Benerator . I'd like to clarify that the Wizard serves primarily as a basic quick start tool. However, we no longer actively maintain it. Instead, our focus is on supporting users who wish to engage more deeply with the core functionalities of the Benerator application.

To get started with the community version of Benerator, we recommend first familiarizing yourself with the basics of the application. For this purpose, we have extensive documentation available [here](https://docs.benerator.de/latest/using_relational_databases.html). Additionally, we've prepared a variety of demos to demonstrate how specific tasks can be accomplished using Benerator scripts. These examples should provide valuable insights into practical applications of the tool.

One such example is the configuration of different database management systems (DBMS). We have a demo environment file available [here](https://github.com/rapiddweller/rapiddweller-benerator-ce/blob/development/src/demo/resources/demo/db/conf/environment.env.properties), which includes configurations for several DBMS to showcase their properties, syntax, and driver paths. The `environment.env.properties` file, which contains these settings, should be placed either next to your `benerator.xml` file or within a subfolder named `conf`. Here's an example of what the contents of this file might look like:

```ini
# conf/environment.env.properties
mysql.db.url=jdbc:mysql://localhost:3306/source
mysql.db.driver=com.mysql.jdbc.Driver
mysql.db.user=root
mysql.db.password=root
mysql.db.schema=source
```

To utilize this configuration, your `benerator.xml` should be set up as follows:

```xml
<!-- benerator.xml -->
<setup>
    <database id="mysql"/>
    <execute type="sql" target="target">
        create table sample (
        id int primary key
        );
    </execute>
    <generate type="sample" count="10" consumer="target"/>
</setup>
```

We hope this information helps you get started with Benerator. Should you have any further questions or require additional assistance, please don't hesitate to reach out.

Best wishes,

Benerator Team

**Comment by roxsyr** [comment]
Thank you! This information help me a lot. I can set the connectio with MySql.
