### ISSUE TITLE
[new] Family Generator

### ISSUE THREAD

**Issue by dhartford** [rapiddweller/rapiddweller-benerator-ce#53]
**Is your feature request related to a problem? Please describe.**
When creating scenarios where various permutations of an immediate family are involved (father, mother, son, daughter | mother, daughter | father, son, daughter | father, stepmother, son, daughter), this has proven challenging with the existing benerator capability.

**Describe the solution you'd like**
this may involve some creative means to solve when intermixed with the PersonGenerator, and ensuring 'relevant' outputs (as it relates to age ranges). A potential output along the lines of:

Person=firstname,lastname,gender,dateofbirth  | Family=familyunitGUID, familyunitrelation

John, Doe,M, 1950-12-01 | 1234, father
Jane, Doe,F, 1954-12-12 | 1234, mother
Bob, Doe, M, 2010-06-06 | 1234, son

Additional challenges around how to quantify/classify same-gender parents, step-relations, adoptions, or divorced relations (in the case a father is divorced but has a son in a different family unit, but may provide some form of legal assistance/insurance that may be relevant for a scenario) as those are actually on a per-person basis rather than family unit relation, however for a first pass I feel like the above could solve mine and potentially other users challenges (and help bring benerator back up into the spotlight!)

**Describe alternatives you've considered**

**Additional context**

**Comment by ake2l** [comment]
Hi , you could easily do 


`<Attribute name="test" values="'father', 'son', 'mother'"/>`

or you can write a Javascript returns based on gender and age the family relationship 

`<Attribute name="test" script="{js: getFamilyRelation(age, gender)}"/>`

Guess there are possibilities to solve this , but you are right , it could be also a nice extension of the person generator .
