### ISSUE TITLE
 More that one element found in search: documentation when generating xml files from XSD schema

### ISSUE THREAD

**Issue by piotr-ghn** [rapiddweller/rapiddweller-benerator-ce#73]
**Describe the bug**

Exception in thread "main" java.lang.IllegalArgumentException: More that one element found in search: documentation
It occurs when in my schema I have two “xs:documentation” items like below:

```
<xs:annotation>
   <xs:documentation source="Name" xml:lang="EN">ProprietaryManagementV03</xs:documentation>
   <xs:documentation source="Definition" xml:lang="EN">It is used by description.</xs:documentation>
</xs:annotation>
```

Do you have any solution for this ?

**To Reproduce**
1. Run from command line 'createXML myschema.xsd root my_tx-{0}.xml 2'
2. See error in command line or log

**Expected behavior**
Benerator should allow create xml files from XSD Schema where many 'xs:documentation' tags exist.

**Desktop (please complete the following information):**
 - Benerator version 1.1.2
 - OS: [Linux Rhel 8.4]
 - Browser [chrome]
 - Version [Version 94.0.4606.54 (Official Build) (64-bit)]

**Comment by vbergmann2** [comment]
This is a bug which we will fix. Until then you have an easy and effective workaround: Use a copy of the XML Schema file and delete the &lt;xs:documentation&gt; elements with a text editor.

**Comment by piotr-ghn** [comment]
Thank you very much for the answer and solution.
In which version of package jar and Benerator the fix will be accessible ?

**Comment by vbergmann2** [comment]
We have fixed the issue and will ship the fix with the next Benerator release.

You can access the fix instantly by checking out the Benerator CE development branch at [https://github.com/rapiddweller/rapiddweller-benerator-ce](https://github.com/rapiddweller/rapiddweller-benerator-ce) and build it with maven 
(`$ mvn clean assembly`).

If you have a Benerator subscription, you can contact us to request an immediate bug fix release.
