### ISSUE TITLE
Tag xs:complexType in XSD schema not generated data

### ISSUE THREAD

**Issue by piotr-ghn** [rapiddweller/rapiddweller-benerator-ce#75]
**Describe the bug**

I have xsd schema configuration like below:

```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="inline">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element ref="external"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="external" type="CustAcc4"/>
    <xs:complexType name="CustAcc4">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="Sts" type="AccStatus3Code"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="AccStatus3Code">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ENAB"/>
            <xs:enumeration value="DESA"/>
            <xs:enumeration value="DELE"/>
            <xs:enumeration value="FORM"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

```

When executing this schema I received like below xml files:

```

<?xml version="1.0" encoding="UTF-8"?>
<root elementFormDefault="unqualified"> 
   <inline>CB29D0GxVkKd9shkOY15h37Bov8Czuf</inline>
    <external/>
</root>

```

Why “external” item is not generated in any xml file ?

**To Reproduce**
1. Run from command line 'createXML myschema.xsd root my_tx-{0}.xml 2'
2. See generated xml files

**Expected behavior**
The Benerator should generate data from such written xs:complexType tags.

**Desktop (please complete the following information):**
 - Benerator version 1.1.2
 - OS: [Linux Rhel 8.4]
 - Browser [chrome]
 - Version [Version 94.0.4606.54 (Official Build) (64-bit)]

**Comment by piotr-ghn** [comment]
Hello,

You assigned this issue to solve in Release 2.1.0. Will it be accessible in all your Benerator versions there ?
When do you plan to have Release 2.1.0 ?

Best regards,
Piotr

**Comment by ake2l** [comment]
Dear Piotr,
feature extensions related to XSD generation will be only accessible in our Enterprise Edition. We are planning a release with a focus on finance formats like PACS at the end of this year.

Best regards,
Benerator Team

**Comment by ake2l** [comment]
has been realised in EE
