### ISSUE TITLE
Element type xs:any not supported in xs:sequence - XSD schema

### ISSUE THREAD

**Issue by piotr-ghn** [rapiddweller/rapiddweller-benerator-ce#76]
**Describe the bug**

Exception in thread "main" java.lang.UnsupportedOperationException: Element type xs:any not supported in xs:sequence 
It occurs when I have in schema items like below: 

```
    <xs:complexType name="SuppDataEnv1">
        <xs:sequence> 
            <xs:any namespace="##any" processContents="lax"/> 
        </xs:sequence> 
    </xs:complexType> 
```

Could you please help with this issue ? 

**To Reproduce**
1. Run from command line 'createXML myschema.xsd root my_tx-{0}.xml 2'
2. See error in command line or log

**Expected behavior**
The Benerator should allow create xml files from XSD Schema where 'xs:any' tags exist.
The 'xs:any' tag can also be generated in xml files.

**Desktop (please complete the following information):**
 - Benerator version 1.1.2
 - OS: [Linux Rhel 8.4]
 - Browser [chrome]
 - Version [Version 94.0.4606.54 (Official Build) (64-bit)]

**Comment by ake2l** [comment]
has been realised in EE
