### ISSUE TITLE
UnsupportedOperationException when xs:choice in xs:complexType

### ISSUE THREAD

**Issue by piotr-ghn** [rapiddweller/rapiddweller-benerator-ce#77]
**Describe the bug**

'Exception in thread "main" java.lang.UnsupportedOperationException: Element type xs:choice not supported in xs:complexType'

I got exception “Element type xs:choice not supported in xs:complexType” when I have items in my schema like below: 

```
    <xs:complexType name="CoActEventType102Choice"> 
        <xs:choice> 
            <xs:element name="Cd" type=" CoActEventType34Code "/> 
        </xs:choice> 
    </xs:complexType> 

    <xs:simpleType name="CoActEventType34Code"> 
        <xs:restriction base="xs:string"> 
            <xs:enumeration value="ACER"/> 
            <xs:enumeration value="ATRT"/> 
            <xs:enumeration value="BRIU"/> 
            <xs:enumeration value="DFHL"/> 
        </xs:restriction> 
    </xs:simpleType> 
```
 

**To Reproduce**
1. Run from command line 'createXML myschema.xsd root my_tx-{0}.xml 2'
2. See error in command line or log

**Expected behavior**

The Benerator should allow create xml files from XSD Schema where configuration of such tags exists.

**Desktop (please complete the following information):**
 - Benerator version 1.1.2
 - OS: [Linux Rhel 8.4]
 - Browser [chrome]
 - Version [Version 94.0.4606.54 (Official Build) (64-bit)]

**Comment by ake2l** [comment]
has been realised in EE
